Document: python-pypiserver-daemon
Title: Debian python-pypiserver-daemon Manual
Author: <insert document author here>
Abstract: This manual describes what python-pypiserver-daemon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-pypiserver-daemon/python-pypiserver-daemon.sgml.gz

Format: postscript
Files: /usr/share/doc/python-pypiserver-daemon/python-pypiserver-daemon.ps.gz

Format: text
Files: /usr/share/doc/python-pypiserver-daemon/python-pypiserver-daemon.text.gz

Format: HTML
Index: /usr/share/doc/python-pypiserver-daemon/html/index.html
Files: /usr/share/doc/python-pypiserver-daemon/html/*.html
